export type Gender = 'male' | 'female'

export interface Client {
  id: string
  user_id: string
  first_name: string
  last_name: string
  birth_date: string | null
  age_years: number | null
  gender: Gender | null
  current_goal: string | null
  physical_notes: string | null
  created_at: string
  updated_at: string
}

export interface ClientInsert {
  first_name: string
  last_name: string
  birth_date?: string | null
  age_years?: number | null
  gender?: Gender | null
  current_goal?: string | null
  physical_notes?: string | null
}

export interface ClientUpdate extends Partial<ClientInsert> {}

export interface GoalHistory {
  id: string
  client_id: string
  goal: string
  started_at: string
  ended_at: string | null
}

export interface GoalInsert {
  client_id: string
  goal: string
  started_at?: string
}

export interface Exercise {
  id: string
  user_id: string | null
  name: string
  description: string | null
  lumio_card_id: string | null
  created_at: string
}

export interface ExerciseTag {
  id: string
  exercise_id: string
  tag: string
  created_at: string
}

export interface ExerciseInsert {
  name: string
  description?: string | null
  lumio_card_id?: string | null
}

export interface ExerciseUpdate extends Partial<ExerciseInsert> {}

export interface ExerciseWithDetails extends Exercise {
  tags?: ExerciseTag[]
  sessionsCount?: number
  plannedSessionsCount?: number
  lumio_card?: LumioLocalCardWithRepository | null
}

export interface Gym {
  id: string
  user_id: string
  name: string
  address: string | null
  description: string | null
  created_at: string
  updated_at: string
}

export interface GymInsert {
  name: string
  address?: string | null
  description?: string | null
}

export interface GymUpdate extends Partial<GymInsert> {}

// Sessions

export type SessionStatus = 'planned' | 'completed'

export interface Session {
  id: string
  client_id: string
  gym_id: string | null
  session_date: string
  status: SessionStatus
  notes: string | null
  current_exercise_index: number
  created_at: string
  updated_at: string
}

export interface SessionInsert {
  client_id: string
  gym_id?: string | null
  session_date: string
  status?: SessionStatus
  notes?: string | null
}

export interface SessionUpdate extends Partial<Omit<SessionInsert, 'client_id'>> {
  current_exercise_index?: number
}

export interface SessionExercise {
  id: string
  session_id: string
  exercise_id: string
  order_index: number
  sets: number | null
  reps: number | null
  weight_kg: number | null
  duration_seconds: number | null
  notes: string | null
  completed: boolean
  completed_at: string | null
  skipped: boolean
  is_group: boolean
}

export interface SessionExerciseInsert {
  session_id: string
  exercise_id: string
  order_index?: number
  sets?: number | null
  reps?: number | null
  weight_kg?: number | null
  duration_seconds?: number | null
  notes?: string | null
  is_group?: boolean
}

export interface SessionExerciseUpdate extends Partial<Omit<SessionExerciseInsert, 'session_id'>> {
  completed?: boolean
  completed_at?: string | null
  skipped?: boolean
  is_group?: boolean
}

export interface SessionExerciseWithDetails extends SessionExercise {
  exercise?: ExerciseWithDetails
}

export interface SessionWithDetails extends Session {
  client?: Client
  gym?: Gym | null
  exercises?: SessionExerciseWithDetails[]
}

// AI Planning

export type AIRole = 'user' | 'assistant' | 'system'

export interface AIConversation {
  id: string
  user_id: string
  client_id: string
  title: string | null
  created_at: string
  updated_at: string
}

export interface AIConversationInsert {
  client_id: string
  title?: string | null
}

export interface AIMessage {
  id: string
  conversation_id: string
  role: AIRole
  content: string
  created_at: string
}

export interface AIMessageInsert {
  conversation_id: string
  role: AIRole
  content: string
}

export interface AIGeneratedPlan {
  id: string
  conversation_id: string
  session_id: string | null
  plan_json: TrainingPlan
  accepted: boolean
  created_at: string
}

export interface AIGeneratedPlanInsert {
  conversation_id: string
  plan_json: TrainingPlan
  accepted?: boolean
}

// Training plan structure generated by AI
export interface TrainingPlanExercise {
  exercise_name: string
  exercise_id?: string | null // Matched exercise from catalog
  sets?: number | null
  reps?: number | null
  weight_kg?: number | null
  duration_seconds?: number | null
  notes?: string | null
}

export interface TrainingPlan {
  gym_id?: string | null
  gym_name?: string | null
  session_date: string
  exercises: TrainingPlanExercise[]
  notes?: string | null
}

export interface AIConversationWithDetails extends AIConversation {
  client?: Client
  messages?: AIMessage[]
  plans?: AIGeneratedPlan[]
}

// Coach AI Settings

export type AIProvider = 'openai' | 'anthropic'

export interface AIModel {
  id: string
  name: string
  provider: AIProvider
}

export const AI_MODELS: AIModel[] = [
  // OpenAI models
  { id: 'gpt-4o', name: 'GPT 4.o', provider: 'openai' },
  { id: 'o3', name: 'GPT 5.1', provider: 'openai' },
  // Anthropic models
  { id: 'claude-3-5-haiku-20241022', name: 'Haiku 4.5', provider: 'anthropic' },
  { id: 'claude-sonnet-4-20250514', name: 'Sonnet 4.5', provider: 'anthropic' },
  { id: 'claude-opus-4-20250514', name: 'Opus 4.5', provider: 'anthropic' },
]

export interface CoachAISettings {
  id: string
  user_id: string
  openai_api_key: string | null
  anthropic_api_key: string | null
  preferred_provider: AIProvider
  preferred_model: string
  helix_mcp_api_key_hash: string | null
  created_at: string
  updated_at: string
}

export interface CoachAISettingsInsert {
  openai_api_key?: string | null
  anthropic_api_key?: string | null
  preferred_provider?: AIProvider
  preferred_model?: string
  helix_mcp_api_key_hash?: string | null
}

export interface CoachAISettingsUpdate extends CoachAISettingsInsert {}

// Lumio Card Types

export interface LumioCardFrontmatter {
  title?: string
  tags?: string[]
  difficulty?: 1 | 2 | 3 | 4 | 5
  language?: string
}

export interface LumioCard {
  frontmatter: LumioCardFrontmatter
  content: string
  baseUrl: string
}

// Lumio Repository Types (Local sync)

export type SyncStatus = 'pending' | 'syncing' | 'synced' | 'error'

export interface LumioRepository {
  id: string
  user_id: string
  name: string
  github_owner: string
  github_repo: string
  access_token: string | null
  docora_repository_id: string | null
  last_commit_hash: string | null
  last_commit_at: string | null
  last_sync_at: string | null
  sync_status: SyncStatus
  sync_error: string | null
  cards_count: number
  last_sync_added: number
  last_sync_updated: number
  last_sync_removed: number
  last_sync_unchanged: number
  created_at: string
  updated_at: string
}

export interface LumioRepositoryInsert {
  name: string
  github_owner: string
  github_repo: string
  access_token?: string | null
}

export interface LumioRepositoryUpdate extends Partial<LumioRepositoryInsert> {}

// Lumio Local Card Types (synced from repositories)

export interface LumioLocalCardFrontmatter {
  title?: string
  tags?: string[]
  difficulty?: number
  language?: string
  [key: string]: unknown
}

export interface LumioLocalCard {
  id: string
  repository_id: string
  user_id: string
  file_path: string
  title: string | null
  content: string
  raw_content: string
  content_hash: string | null
  frontmatter: LumioLocalCardFrontmatter | null
  source_available: boolean
  created_at: string
  updated_at: string
}

export interface LumioLocalCardWithRepository extends LumioLocalCard {
  repository?: LumioRepository
}

export interface LumioCardImage {
  id: string
  card_id: string
  original_path: string
  storage_path: string
  created_at: string
}

// Group Templates

export interface GroupTemplate {
  id: string
  user_id: string
  name: string
  created_at: string
  updated_at: string
}

export interface GroupTemplateInsert {
  name: string
}

export interface GroupTemplateUpdate extends Partial<GroupTemplateInsert> {}

export interface GroupTemplateExercise {
  id: string
  template_id: string
  exercise_id: string
  order_index: number
  sets: number | null
  reps: number | null
  weight_kg: number | null
  duration_seconds: number | null
  notes: string | null
  created_at: string
}

export interface GroupTemplateExerciseInsert {
  template_id: string
  exercise_id: string
  order_index?: number
  sets?: number | null
  reps?: number | null
  weight_kg?: number | null
  duration_seconds?: number | null
  notes?: string | null
}

export interface GroupTemplateExerciseUpdate
  extends Partial<Omit<GroupTemplateExerciseInsert, 'template_id'>> {}

export interface GroupTemplateWithExercises extends GroupTemplate {
  exercises?: GroupTemplateExerciseWithDetails[]
}

export interface GroupTemplateExerciseWithDetails extends GroupTemplateExercise {
  exercise?: ExerciseWithDetails
}
